apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 992382830933.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:8bf886f14a59a25af254da43fbbb1d47c6da699c
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: electronics-service
  labels:
    app: electronics
spec:
  type: ClusterIP
  selector:
    app: electronics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
